---
- name: Deploy Podman Application
  hosts: all
  gather_facts: false
  tasks:
    - name: Update Quadlet Image Tag
      shell: |
        sudo sed -i "s|^Image=.*|Image=148737623247.dkr.ecr.us-east-2.amazonaws.com/podman-demo:{{ new_git_sha }}|g" /etc/containers/systemd/podman-demo.container
      
    - name: Deploy Podman Policy
      shell: |
        sudo cp /home/ubuntu/podman-demo/server-config/policy.json /etc/containers/policy.json

    - name: Authenticate Podman with AWS ECR
      shell: |
        sudo aws ecr get-login-password --region us-east-2 | sudo podman login --username AWS --password-stdin 148737623247.dkr.ecr.us-east-2.amazonaws.com
      
    - name: Restart Podman application
      shell: |
        sudo systemctl daemon-reload
        sudo systemctl restart podman-demo
